---
# To enable a rpm repo on servers
- name: get bosapa details
  hosts: all
  gather_facts: no
  remote_user: root
  become: true
  ignore_errors: yes
  tasks:
    - name: This will enable the repo
      shell: subscription-manager repos --enable rhel-7-server-satellite-tools-6.9-rpms;
      args:
        executable: /bin/bash
      register: shell_result

    - debug:
        var: shell_result.stdout_lines
